### ISSUE TITLE
Bug in 'reverse' filter

### ISSUE THREAD

**Issue by al-martyn1** [jinja2cpp/Jinja2Cpp#225] opened 2022-04-25 22:32 UTC
```
    std::vector<std::string> foundTypes;
    jinja2::ValuesMap renderParams = 
    {   { "specTypes"    , jinja2::Reflect(&foundTypes)  }
    };
// ...

    if (...)
    {
        foundTypes = ...
        renderParams["specTypes"] = jinja2::Reflect(&foundTypes);
    }
```

Also, simple jinja makes the same effect:
```
{{ [3, 1, 2] | reverse }}
```
produces the bad_expected_access exception, which inspired by std::bad_alloc exception

```
// filters.cpp:452
InternalValue SequenceAccessor::Filter(const InternalValue& baseVal, RenderContext& context)
//...
// filters.cpp:479
listSize = {has_value_=true (0x34) contained={data={_Val=6.951334341138e-310#DEN _Pad=0x000000750f548880 "\x1ЉGyц" } } }
// 0x34 - 52 - size of my data vector
// requested size: size = 0x00007ff679478a01
// hex representation of 6.951334341138e-310 double is 0x00007ff679478a01
```

**Comment by rmorozov** [comment] 2023-06-23 13:44
std::vector<std::string> foundTypes;
    jinja2::ValuesMap renderParams = 
    {   { "specTypes"    , jinja2::Reflect(&foundTypes)  } // moving foundTypes
    };

    // ...

    if (...)
    {
        foundTypes = ...
        renderParams["specTypes"] = jinja2::Reflect(&foundTypes); // UB
    }


Looks like UB, because of using moved from object.
According to contract mentioned in [doc](https://github.com/jinja2cpp/Jinja2Cpp/blob/master/include/jinja2cpp/reflected_value.h#L27) 

std::vector<std::string> foundTypes was moved on the first jinja2::Reflect usage

and in your case for [vector](https://github.com/jinja2cpp/Jinja2Cpp/blob/master/include/jinja2cpp/reflected_value.h#L411)

Closing this issue.


Feel free to reopen if you have another problem reproduce scenario for reverse filter.

**Closed by rmorozov** 2023-06-23 13:44 UTC
